In [12]:
!pip install keras-tuner #run only once and then delete 

  Using cached keras_tuner-1.1.2-py3-none-any.whl (133 kB)
  Using cached kt_legacy-1.0.4-py3-none-any.whl (9.6 kB)


In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
print(tf.__version__)

2.9.1


In [3]:
fashion_mnist=keras.datasets.fashion_mnist

In [4]:
(train_images,train_labels),(test_images,test_labels)=fashion_mnist.load_data()

In [5]:
train_images=train_images/255.0
test_images=test_images/255.0

In [6]:
train_images[0].shape
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [7]:
train_images=train_images.reshape(len(train_images),28,28,1)
test_images=test_images.reshape(len(test_images),28,28,1)

In [8]:
#two types selectors functions: 1. INT  2. Choice
def build_model(hp):  
  model = keras.Sequential([
    keras.layers.Conv2D(
        filters=hp.Int('conv_1_filter', min_value=32, max_value=128, step=16),#min value of filter you want
        kernel_size=hp.Choice('conv_1_kernel', values = [3,5]),#picks like mcq
        activation='relu',
        input_shape=(28,28,1)
    ),
      #for i in range(0,hp.Int(....)) this will also work
    keras.layers.Conv2D(
        filters=hp.Int('conv_2_filter', min_value=32, max_value=64, step=16),# ihave added this line extra in comparison to the old model
        kernel_size=hp.Choice('conv_2_kernel', values = [3,5]),
        activation='relu'
    ),
    keras.layers.Flatten(),
    keras.layers.Dense(
        units=hp.Int('dense_1_units', min_value=32, max_value=128, step=16),
        activation='relu'
    ),
    keras.layers.Dense(10, activation='softmax')
  ])
  
  model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', values=[1e-2, 1e-3])),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
  
  return model

In [9]:
from keras_tuner import RandomSearch
from keras_tuner.engine.hyperparameters import HyperParameters
#hyprer/paramter tuning

In [10]:
tuner_search=RandomSearch(build_model,
                          objective='val_accuracy',
                          max_trials=5,directory='output',project_name="Mnist34569Fashion")

INFO:tensorflow:Reloading Oracle from existing project output\Mnist34569Fashion\oracle.json
INFO:tensorflow:Reloading Tuner from output\Mnist34569Fashion\tuner0.json


In [11]:
tuner_search.search(train_images,train_labels,epochs=3,validation_split=0.1)

INFO:tensorflow:Oracle triggered exit


In [12]:
model=tuner_search.get_best_models(num_models=1)[0]

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 48)        480       
                                                                 
 conv2d_1 (Conv2D)           (None, 24, 24, 48)        20784     
                                                                 
 flatten (Flatten)           (None, 27648)             0         
                                                                 
 dense (Dense)               (None, 64)                1769536   
                                                                 
 dense_1 (Dense)             (None, 10)                650       
                                                                 
Total params: 1,791,450
Trainable params: 1,791,450
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(train_images, train_labels, epochs=10, validation_split=0.1, initial_epoch=3)

Epoch 4/10
1688/1688 [==============================] - 19s 6ms/step - loss: 0.1322 - accuracy: 0.9504 - val_loss: 0.2684 - val_accuracy: 0.9152
Epoch 5/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.0974 - accuracy: 0.9635 - val_loss: 0.2867 - val_accuracy: 0.9132
Epoch 6/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.0673 - accuracy: 0.9757 - val_loss: 0.3482 - val_accuracy: 0.9097
Epoch 7/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.0502 - accuracy: 0.9820 - val_loss: 0.3660 - val_accuracy: 0.9167
Epoch 8/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.0375 - accuracy: 0.9867 - val_loss: 0.4335 - val_accuracy: 0.9110
Epoch 9/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.0297 - accuracy: 0.9892 - val_loss: 0.4598 - val_accuracy: 0.9092
Epoch 10/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.0240 - accuracy: 0.9915 - val_loss: 0.5061 - val_a

In [22]:
z=model.predict(test_images)

313/313 [==============================] - 1s 3ms/step


In [23]:
z1=np.argmax(z,axis=1) 

In [24]:
print(z1)

[9 2 1 ... 8 1 5]


In [25]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(z1,test_labels)

0.9055

In [24]:
from joblib import dump,load

In [25]:
dump(model,'basic.joblib')

INFO:tensorflow:Assets written to: ram://452e1931-065c-4648-b948-8dfa82197afc/assets


['basic.joblib']

In [ ]:
#create a hypertuned model on flower dataset already sent to you
#final week:
# 1. read YOLO  material
# 2. try to use yolo on your own
# 3. read about video to image conversion on youtube(search video to frames and then back on youtube)//i will provide link
# on next wednesday our project will be over.
# submit all due assignments by then
#deadline for this ill be 19th and todays assignment will be 19h for y20s and y19s
# for 21s assignments must be submitted before 22nd.